### ISSUE TITLE
Issue compiling MODBUS library

### ISSUE THREAD

**Issue by iMarvinS** [esp8266/Arduino#10]
Hello!
I just wanted to compile the arduino-modbus-slave library (https://code.google.com/p/arduino-modbus-slave/downloads/detail?name=MODBUS.zip&can=2&q=) which seems to be perfectly compatible with the ESP8266 Arduino SDK because it only uses the Serial library which is fully adopted.
When I try to compile my sketch which depends on the MODBUS library I get the following error: 
![bildschirmfoto 2015-03-29 um 15 21 24](https://cloud.githubusercontent.com/assets/7142039/6885609/f0081af4-d627-11e4-8ad7-a55a682a2463.png)

Does anybody know where the issue is?
It seems to be an issue with the xtensa toolchain but I cannot find out what it is.

Kind Regards
Marvin

**Comment by igrr** [comment]
The issue is because the library seems to use malloc function, which is not
available. There are three ways to fix that:
- replace malloc and free with new and delete in the library
- replace malloc and free with os_malloc and os_free which are defined in
ESP SDK
- fix ulibc to use os_malloc instead of malloc.

**Comment by igrr** [comment]
A lot of people seem to be having issues related to malloc, so I created #11 to track it.

**Comment by iMarvinS** [comment]
Thank you! 
I replaced all malloc and free calls with their corresponding C++ equivalents (new and delete).
Now the library works flawless on the ESP as well as the Uno.
This issue is resolved now.

Thanks

**Comment by gkrananth** [comment]
Can you please share the library
