### ISSUE TITLE
Mesh Mode non functional

### ISSUE THREAD

**Issue by ibaranov-cp** [esp8266/Arduino#1093]
Hello all,

Using latest staging version, RC2 from board manager.
I have two identical ESP8266-12E modules.
I load them both with the example Mesh code.
I add in a Serial.println("."); into the loop to ensure they are both working.

Both modules wait endlessly.

Does this feature work at all?
##

**Comment by igrr** [comment]
Softap is broken in 2.0.0-rc2 (see #1054), i think this might be the reason for mesh library to have issues.
That said, the author of mesh library doesn't seem to be around any more, so it isn't really maintained any more.

**Comment by ibaranov-cp** [comment]
Issue #1054 doesn't seem to be the cause here, I have the fixed version.
Will try and figure out root cause here.

**Comment by battuashwik** [comment]
Any luck with the mesh library ?

**Comment by Makuna** [comment]
The Esp8266WifiMesh library is not really a good implementation.  Due to being completely open, how synchronous it is written, and that it requires string messages (memory fragmentation from string class and binary data transmission requires conversion to text), its not something to base any serious project on. 

It maybe great to play with though.

**Comment by devyte** [comment]
@ibaranov-cp is this issue still valid with latest git?

**Comment by ibaranov-cp** [comment]
Unknown, sorry I don't have bandwidth to test this in the near future.

**Comment by devyte** [comment]
Ok, closing due to age. If there is still a problem, please open a new issue.
