### ISSUE TITLE
yield() effect in delay()

### ISSUE THREAD

**Issue by gioblu** [esp8266/Arduino#1410]
How much coherent with the requested value is the delay time produced, and how much is affected by yield() and so execution of other tasks? Can this lead to overshoot the requested time?
If this happens maybe yield() function should be called consciously by user and not forced inside delay(), not to influence some use cases like bit-banging.

**Comment by igrr** [comment]
Short answer: delay actually operates by doing a context switch (via
esp_yield), it's just how it is implemented. Other tasks may affect timing,
but on a single core network processor this is pretty much inevitable.

delayMicroseconds doesn't do a context switch, so if you want bitbanging
you should probably use that instead of delay.

**Comment by gioblu** [comment]
Perfect, is the answer I was hoping for :)
Thank you!

**Comment by asetyde** [comment]
Sorry Igor but I  not clear clearly , context switch can be a factor of block device ? Sometimes my device it block with connector MySQL , I use a conter to escape from delay in function but to work connector need pauses , which of this function Delay or delay micro. Is best to do this more safely possible

**Comment by Links2004** [comment]
if you need to "pauses" be course you wait for data you need to use delay or yield,
or you will never get data (the network stack need to run).

**Comment by asetyde** [comment]
But difference delay() and yield
