### ISSUE TITLE
ESP.eraseConfig() does not seem to clear SDK Wifi Credentials

### ISSUE THREAD

**Issue by hallard** [esp8266/Arduino#1494]
Does the `ESP.eraseConfig()` should also erase SDK Wifi Credentials ? 
I've 2 button on my Web Interface to do 
* Reset (just reset the board)
* Factory Reset to clear all and reset.

Factory Reset restore my default board config settings including clearing my client SSID and PSK, and then call a `ESP.eraseConfig()`to also clear SDK config. Then issue a normal reset.

Unfortunately, just after Factory Reset, my board reset and then connect to my Old Access point even if I don't call Wifi setting and connection (because my config is empty on those settings, yeah cleared that!!)
Anyone tried this with success ?

**Comment by igrr** [comment]
I think if you do `ESP.restart()` after `ESP.eraseConfig()`, SDK libraries will actually restore the configuration from RAM before restarting. I'm not sure this is documented, but I saw this while going through disassembly of some older version of the SDK (1.0.0-like).
You could try to crash instead of calling `restart`, i.e. do something like `*((int*) 0) = 0;`. It's not a clean solution, though. I would prefer if the SDK didn't do something under the hood unless instructed to do so explicitly, but well... I guess it's a task for another time.

**Comment by hallard** [comment]
@igrr 
you're absolutely right, It did the trick ;-)
I just replaced 
```
*((int*) 0) = 0;
```
by a watchdog reset, it works but is it correct ?
```
// Fire Watchdog Reset
while(1);
```
thanks

**Comment by Links2004** [comment]
```cpp
ESP.reset();
```
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Esp.cpp#L116

**Comment by hallard** [comment]
@didn't tried that one, it will not restore config like restart() ?

**Comment by Links2004** [comment]
yes (last tried on SDK 1.3),
its simple a other way too reset the ESP.
more clean then WDT or triggering a exception.

**Comment by barsznica** [comment]
WiFi.disconect() worked for me first go.

ESP.eraseConfig then ESP.reset() OR ESP.eraseConfig() then ESP.restart() did not work for me.
I did not try the *((int*) 0) = 0; thing.

The answer to this question was covered [here](https://github.com/tzapu/WiFiManager/issues/142) and [here](http://www.esp8266.com/viewtopic.php?f=32&t=8204&start=4).
