### ISSUE TITLE
Timer1 causing resets

### ISSUE THREAD

**Issue by bjpirt** [esp8266/Arduino#1538]
I'm trying to use timer1 to accurately drive some stepper motors using interrupts but I've run into a problem where when I use it, the Arduino will reset every 10 or so seconds. I've boiled down the code to this:

```C
void timer_callback(void){
  digitalWrite(13, !digitalRead(13));
}

void setup() {
  pinMode(13, OUTPUT);
  
  timer1_disable();
  timer1_attachInterrupt(timer_callback);
  timer1_enable(TIM_DIV1, TIM_EDGE, TIM_LOOP);
  timer1_write(1);
}

void loop() {
  delay(0);
}
```

Any ideas what I'm doing wrong? Also, I'd love to know what the number passed into timer1_write represents - it seems to be about 2 and a bit microseconds.

**Comment by igrr** [comment]
You need to mark your timer callback with ICACHE_RAM_ATTR.

**Comment by bjpirt** [comment]
That doesn't seem to have any effect unfortunately - still resets exactly the same :-(

**Comment by bjpirt** [comment]
Figured it out - it needed `timer1_isr_init();` in there before enabling it.

**Comment by ThoughtFisher** [comment]
This is the answer to your problem bro:

void timer_callback(void){
  digitalWrite(2, !digitalRead(13));
  Serial.println("1");
  wdt_reset();
}
void setup() {
pinMode(2, OUTPUT);
 Serial.begin(115200);
  timer1_disable();
  timer1_attachInterrupt(timer_callback);
  timer1_isr_init();
  timer1_enable(TIM_DIV1, TIM_EDGE, TIM_LOOP);
  timer1_write(1000);

  //Set up ESP watchdog
  ESP.wdtDisable();
  ESP.wdtEnable(WDTO_8S);
}
void loop() {
  
}

you had problems with the watchdog because you dont have lines, then  watchdog detect inactivity and reset the esp8266 supposing an error.

**Comment by kamalesh07** [comment]
i want to use timer as well as i need to receive data from mobile through wifi how it is possible
