### ISSUE TITLE
Arduino IDE

### ISSUE THREAD

**Issue by PhilColbert** [esp8266/Arduino#1934]
Is there any reason all the options for debugging in the IDE just on the Generic ESP8266 option and not on the rest of the boards, ie on the Nodemcu boards?

Thanks

**Comment by t3chguy** [comment]
All the other variants are just preconfigured versions of the "Generic ESP8266"
None of the boards feature USB/Serial on the Debug UART so that's why do not have a Debug option, if you're at the point where you're attaching USB/Serial to Debug, you'll probably have other settings tweaked too and will be using the "Generic ESP8266" which has no pre-chosen configuration values so to speak.

**Comment by PhilColbert** [comment]
Thanks for the reply, sorry for the newbie questions, still learning here ! :)
