### ISSUE TITLE
ESP in dual mode, AP and station 

### ISSUE THREAD

**Issue by ranjit84** [esp8266/Arduino#2441]
I have configured my esp in dual mode and it works fine. 
I have few queries - 
1.  I can check a gpio pin and use single mode at a time. either station or AP, right now its in dual mode and I face one problem, sometimes my web html page are not served whole, they are broken. I have used SPIFFS liberary to store web pages. Seems like some memeory issue. 
So my quesiotn is is this really a memory problem because thre are lot of checks and variables involved int the loop() method. 
Having one mode can be also one option, like i can cofigure the mode by check gpio pin status, whether in AP mode or STation mode. Is this better approach. 
2. In dual mode, can I set static IP for my AP and let system have dynamic IP for station mode, what is the correct way of giving static IP in Dual mode for AP 

thanks

**Comment by WereCatf** [comment]
About HTML-pages not being served whole: I've seen several people complaining about similar issues lately and I think it's a bug with the ESP8266-core itself, not in your code. Have you tried an older version of the core, like e.g. 2.2.0, to see if it works any better?

**Comment by devyte** [comment]
@ranjit84 The ESP has a single radio, shared between STA and AP. In dual mode, the SoftAP must be set to the same channel as the STA that you connect to. If you don't, once the STA connects, the SoftAP will be dragged along, and you'll lose connectivity.
In addition, there are some issues with serving webpages with ESP8266WebServer, especially when the webpages have embedded elements. In such cases, modern browsers tend to get creative and try to retrieve concurrenly.
Assuming the issue is still relevant, please try:
- latest git
- PR #3215 (sdk 2.1.0)
- PR #3362 (lwip2)
- ESPAsyncWebServer (an almost drop-in replacement webserver, which is what I currently use without issues)
Please report back here what works.

**Comment by devyte** [comment]
Closing due to lack of feedback in over 2 months, and age.
