### ISSUE TITLE
EEPROM size maximum in ESP8266-01

### ISSUE THREAD

**Issue by lucasmaziero** [esp8266/Arduino#2632]
#### Hardware
Hardware: ESP-01
Core Version: 2.3.0

### Description

Hello
it is possible to allocate eeprom with 4096 bytes in ESP8266-01 ```EEPROM.begin(4096)``` or are 512bytes maximum ```EEPROM.begin(512)```, the question is can I use ```EEPROM.begin(4096)``` without any problems?

**Comment by krzychb** [comment]
Hi @lucasmaziero,

You should be able to use `EEPROM.begin(4096)`without any problems on ESP8266.

Accoriding to current implementation of EEPROM library, 4096 bytes is the [maximum what you can get]( https://github.com/esp8266/Arduino/blob/master/libraries/EEPROM/EEPROM.cpp#L54-L55) because `SPI_FLASH_SEC_SIZE` defined elsewhere = 4096.

**Comment by lucasmaziero** [comment]
Thank you @krzychb
