### ISSUE TITLE
[Question/Idea] Idea for further improvement

### ISSUE THREAD

**Issue by wizziLalev** [esp8266/Arduino#2668]
Hello,
Thanks for the great work!!!

I have an idea and I want to share it and ask you is it possible at all, so:

Currently entire OTA update is relying on the fact that all sketches are small enough to keep the current and the new sketch in the memory during the update process - please correct me if I'm wrong! But what IF the sketch is bigger?

Is it possible to use external EEPROM to keep the new sketch during the process or even better will be to have 2 separate external EEPROMs (one for the "old" sketch and one for the "new" one) just for redundancy? Of course this will occupy at least 2 IO pins but I think this can be accepted.

I want to see what you can say about this idea. Thanks!

**Comment by devyte** [comment]
@wizziLalev Thank you for your enthusiasm. For most users, this means custom hardware, as opposed to the standard cheap boards available today. Then, many users care about low power usage, so additional hardware is a big no.
Rather than have an external EEPROM, it is possible to just change the flash chip for a bigger one. Today you can get ESPs with 4MB for under usd$3, shipping included, and 16MB for about usd$5. That's more than enough for a huge sketch, plus an onboard file system.
Closing.
