### ISSUE TITLE
Issue in Client.print

### ISSUE THREAD

**Issue by Navid007** [esp8266/Arduino#2791]
I am using very simple code to send a url via get.

There is no error if I use below code : 
 
 String url= " 123........500"   // 500 charecters...

client.print(String("GET ") + url + " HTTP/1.1\r\n" +
               "Host: " + host + "\r\n" + 
               "Connection: close\r\n\r\n");

but if i do following:

String url ="1";
url +="2";
url +="3";
url +="4";
url +="5";
// .
//.
//.

url +="500";

client.print(String("GET ") + url + " HTTP/1.1\r\n" +
               "Host: " + host + "\r\n" + 
               "Connection: close\r\n\r\n");

Then I get bad request code 400

Anybody knows why ESP can not handle String properly ? Is it because of SRam ? Is there any other way to hanle this issue? When I serial print the url it is OK it shows "1234....500"
The code is correct, if use only 3 or 4 times url +=" something" it works, otherwise it doesn't.

I am getting confused for more than 3 hours and not able to figure out. Your help in this regard is appreciated.

Thanks
Navid

**Comment by devyte** [comment]
@Navid007 no MCVE sketch, no basic info, no IDE settings.
I am using String-concats myself, and I don't have a problem, although I'm not doing 500 concats in a row. 
I suppose it's possible that you are running into heap fragmentation, and at some point String fails to grow (realloc can fail silently), but I'd think that you have some typo or mistake somewhere in your code.
e.g.: in the first code, your string starts with a space, while in your concat code it doesn't.
I suggest debugging your code carefully by printing out the resulting strings. Use start-end markers to "see" all the chars.
Closing due to lack of info, and most likely user error. If you still think the issue exists after careful debgging, feel free to open a new issue, and provide all the details requested in the issue template.
