### ISSUE TITLE
ArduinoOTA : how to disable OTA?

### ISSUE THREAD

**Issue by clyss** [esp8266/Arduino#2797]
Hello,
before initialising ArduinoOTA, no OTA is possible..
is it possible to disable the ArduinoOTA process, and liberate the server port (and perhaps memory used ?)

Of course, in this case, the ArduinoOTA.handle() will have been probably to be something like..:
if (ArduinoOTA.state()....) ArduinoOTA.handle() ;
Thanks

**Comment by devyte** [comment]
@clyss If you use the ArduinoOTA lib, you get both the implementation and the global singleton class, which doesn't have a method for shutting it down. Because the global singleton is already in the lib, you can't declare your own.
However, looking at ArduinoOTA.h, I see the following:

```
#if !defined(NO_GLOBAL_INSTANCES) && !defined(NO_GLOBAL_ARDUINOOTA)
extern ArduinoOTAClass ArduinoOTA;
#endif
```

And there is a similar conditional in ArduinoOTA.cpp. This means that if you #define NO_GLOBAL_ARDUINOOTA at project scope (i.e.: pass the define to the compiler), then you can force not creating the global singleton, and then you can declare your own.
Why do this? Instead of a global object, you can declare a global pointer, and create the object dynamically with new. When you want to shut it down, you can delete the pointer, which calls the object destructor.

Having said that, this is not the right place to ask for assistance. Closing as off topic, see #3655 .
