### ISSUE TITLE
ESP8266 - Change the SSID sending interval

### ISSUE THREAD

**Issue by piccininsouza** [esp8266/Arduino#2862]
Sorry, I don't know if this is the best place to that question, but, is there a way to change de TBTT (Target Beacon Transmission Time) in ESP8266-01?

**Comment by devyte** [comment]
@piccininsouza currently there is no interface in the WiFi class. However, there is an SDK api from Espressif.
Also, you can change the beacon time as a local change for your own use inside ESP8266WiFiAp.cpp, just search for beacon_interval, you'll find it's hardcoded to 100.
Closing due to off-topic, see #3655 .
