### ISSUE TITLE
udp recived packets number

### ISSUE THREAD

**Issue by el3ctrician** [esp8266/Arduino#2928]
hello,
i would like to know if there is a way to get the number of packets in udp buffer and also to set the packet len according to the payload ?

thanks in advance

**Comment by wuwx** [comment]
did you mean this:

int packetSize = Udp.parsePacket();

**Comment by el3ctrician** [comment]
nope, according to the header file [WiFiUdp.h](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/WiFiUdp.h) this wuold return the size of the packet in bytes. I think it's refearing to the first packet. So my question is how can i get the total number (and not size) of packets recived in the Udp buffer ?

**Comment by el3ctrician** [comment]
@igrr if it's not implemented i can try to do if you can kindly guide me from where should i start ?

**Comment by igrr** [comment]
Take a look at UdpContext.h. There is a pbuf chain there, you can add a method to count the number of pbufs in the chain.

**Comment by devyte** [comment]
@el3ctrician did you get around to implementing this? do you want to make a PR?

**Comment by el3ctrician** [comment]
@devyte  i didn't have enough time to do it since the project that i was working on got cancelled, but i would like to try to implement it so maby i'll fork the code for a try this weekend ...

**Comment by devyte** [comment]
Ok, post results or ask questions here.

**Comment by el3ctrician** [comment]
well actually i just saw that the pbuf in the udpContext is a  udp_pcb struct type, so it is a linked list right ? i need to count by checking the  udp_pcb.next right?

**Comment by d-a-v** [comment]
The pbuf api is [lwip's](http://www.nongnu.org/lwip/2_0_x/group__pbuf.html).

WiFiUdp through UdpContext makes use of it: ```_recv()``` is called when a packet is received, filling ```_rx_buf ``` which is a pbuf, using ```pbuf_cat()```. It makes the pbuf grow and it *does not* chain (in the linked list way) the new incoming data. So ```pbuf->len == pbuf->tot_len``` and next is always null.

The notion of packet is then wiped out showing udp's incoming data to the user as a stream, which is what it really is (```class UDP: public Stream```) but not compatible with the "datagram" way of thinking with udp.
Is that your initial concern ?

If this had to be changed, ```pbuf_chain()``` would have to be used instead of ```pbuf_cat()``` along with the linked list management. That would put malloc under less stress and restore the notion of packet if this had to be needed.

**Comment by devyte** [comment]
I am closing this due to age and lack of feedback.
If there is still an idea to be contributed regarding this topic, please open a new issue, follow the template instructions, and explain the idea in detail.
