### ISSUE TITLE
Add comment to documentation - how to prevent to loose the socket

### ISSUE THREAD

**Issue by robertgregor** [esp8266/Arduino#2958]
Hello,

I was struggling now for a long time with random lost of Web server and MQTT connection. Finally, I have discovered, that the reason for this is, if I do some heavy operation in the loop - like I was reading data from Flash and did encryption and I did it in loop. I have discovered, that after that, the mqtt client (which use Client lost the TCP connection with status error and even, I was not able to create the connection again. And I have also lost the http web server, which stopped to work simply. After I put the delay(10) in that heavy operation, everything work fine. I think, it is because the ESP FW needs delay to do some socket maintenance operation in the background, so this let the ESP FW to do it. I think, it would be good to put this to the documentation, for the others to know this...

**Comment by devyte** [comment]
Thank you for your suggestion.
It is part of the espressif documentation that you can't hog the CPU for user code for more than certain short periods of time (i.e.: max callback time, or task times). You _must_ return control to the underlying SDK every so often to allow servicing the wifi stack, otherwise it blows up. This is part of normal usage.
In case of the loop, you can use yield or delay to temporarily return control to the SDK, and then coninue your heavy duty code (even so, this has limitations).
In case of async callbacks, you can't use yield or delay, so you must break up your code into smaller pieces and use a global state machine.
In case of ISRs, there are even more stringent restrictions about time spent in user code.
These are all documented in one place or another*.
Closing.

*Documentation can always be improved. Care to investigate the current docs and contribute per your own suggestion? If so, feel free to open a PR.
