### ISSUE TITLE
Strange output on serial port when reset ESP

### ISSUE THREAD

**Issue by tomaszmacnar** [esp8266/Arduino#3047]
#### Hardware
Hardware:			ESP-07
Core Version:      	2.3.0

### Description

When upload any program (for example Blink) I have output (like in screen) on serial port. I need to have clean console. How to fix it ?
![outut2](https://cloud.githubusercontent.com/assets/26419756/23923983/32acb430-0909-11e7-8d28-3e360bb83908.PNG)

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		1MB
CPU Frequency:	80Mhz
Flash Mode:		DIO
Flash Frequency:	40Mhz
Upload Using:		no_ide_how_it_check
Reset Method:		ck

**Comment by lrmoreno007** [comment]
It is normal in ESP8266 and is independent of the framework you use. Espressif says it can not be disabled.

But you can try transmitting with Serial1 as TX and receiving Serial as RX.
https://github.com/esp8266/Arduino/blob/master/doc/reference.md#serial

**Comment by tomaszmacnar** [comment]
Thanks for answear. I will check this solutions soon :)

**Comment by davisonja** [comment]
For completeness:
It's a start up message from the espressif bootloader and is at 74880 baud.
Or the baud rate set for a soft reset (as opposed to a power cycle)


On 15/03/2017 7:26 pm, "tomaszmacnar" <notifications@github.com> wrote:

Thanks for answear. I will check this solutions soon :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/esp8266/Arduino/issues/3047#issuecomment-286652444>,
or mute
the thread

**Comment by lrmoreno007** [comment]
No, it's a boot log from the ROM. For that reason Espressif can't deactivate it, at least that's what they say.

**Comment by davisonja** [comment]
Yes, the ROM bootloader. Which, among other things, outputs log information on the reset cause and the boot mode.

> https://github.com/espressif/esptool/wiki/ESP8266-Boot-ROM-Log

covers it.

**Comment by devyte** [comment]
Those messages can't be avoided on the main serial port. If you need a clean startup, please follow the suggestions above.
Closing.

**Comment by SergiuToporjinschi** [comment]
That is a serious problem. I spent a week debugging a circuit of a DHT and ESP8266-01 and because I was using GPIO2 (which is also a serial TXD1) and the esp is throwing this boot message on all Serials it seems. So, on ESP8266-01 only one pin available, and that is GPIO-0
