### ISSUE TITLE
Unable to link SDK library ssl (espconn.h) against sketch using ESP8266HTTPClient.h (AXTLS)

### ISSUE THREAD

**Issue by to-scho** [esp8266/Arduino#3409]
### Basic Infos
Unable to link SDK library ssl (espconn.h) against sketch using ESP8266HTTPClient.h (AXTLS)

#### Hardware
Hardware:			ESP-12
Core Version:      	3.4.1a5

### Description

In a sketch I need to combine use of ESP8266HTTPClient.h and some code requiring SDK functions from espconn.h (e.g. espconn_secure_send, espconn_secure_ca_disable, espconn_secure_set_size, espconn_secure_connect). 

Use of espconn.h works fine adding -lssl build flag (platformio setup) when no ESP8266HTTPClient.h is used. Same for ESP8266HTTPClient.h being used without build flag -lssl.  

During linking I got the following errors:

/Users/tobias/.platformio/packages/framework-arduinoespressif8266/tools/sdk/lib/libaxtls.a(tls1.o): In function `finished_digest':
/Users/igrokhotkov/e/axtls/e1/ssl/tls1.c:142: multiple definition of `ssl_ctx_new'
/Users/tobias/.platformio/packages/framework-arduinoespressif8266/tools/sdk/lib/libssl.a(ssl_tls1.o):(.irom0.text+0x20): first defined here
/Users/tobias/.platformio/packages/framework-arduinoespressif8266/tools/sdk/lib/libaxtls.a(tls1.o): In function `finished_digest':
/Users/igrokhotkov/e/axtls/e1/ssl/tls1.c:316: multiple definition of `add_cert'
/Users/tobias/.platformio/packages/framework-arduinoespressif8266/tools/sdk/lib/libssl.a(ssl_tls1.o):(.irom0.text+0x278): first defined here

### Settings in IDE

Module:  			esp01_1m
Flash Size: 		        1MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	        ?
Upload Using:		SERIAL
Reset Method:		?

### Sketch

...
#include <ESP8266HTTPClient.h>
...
HTTPClient httpClient;
...

build_flags = -Wl,-Tesp8266.flash.1m0.ld  -lssl

**Comment by igrr** [comment]
espconn_secure* functions have not been ported to the axTLS fork which we use. axTLS library provided by Espressif is not open source, so one can only guess how these espconn_secure* functions have to be implemented.

If you include both Espressif-provided libssl and the open source libaxtls.a, you get "multiple definition" errors because both libraries define same symbols. It is not feasible to modify libssl.a to use axTLS version provided in libaxtls.a for two reasons:
1. libssl.a is not open source, hence can not be recompiled, so only symbol renaming tricks are possible
2. libssl.a and libaxtls.a use different and incompatible versions of axTLS.
