### ISSUE TITLE
How to increase maximum number of client in AP - ESP8266 (I have connect 4 client at a time but want to connect more than 10)

### ISSUE THREAD

**Issue by aatronics** [esp8266/Arduino#3469]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by devyte** [comment]
@aatronics look at WiFi source code, I think I saw a define somewhere.
This is limited because of _Reasons_. Increasing it will have an impact on memory, which is already pretty scarce.
This is not the right place to ask such questions. This is an issue tracker, meant to track issues in the core. Please refer to esp8266.com or stackoverflow.
Closing as off topic.
