### ISSUE TITLE
Wifi Encryption Type error?

### ISSUE THREAD

**Issue by beicnet** [esp8266/Arduino#3485]
Hi there,

I'm trying to use/get encryption type data from connected device:
`WiFi.encryptionType();`

but, I got error message instead while compiling the sketch:
`no matching function for call to 'ESP8266WiFiClass::encryptionType()'`

I have include and I'm using core version 2.3.0 on WeMos D1 mini:
`#include <ESP8266WiFi.h>`

Can someone tell me why is it not working?

Thank you!

Regards

p.s. I wish to get encryption type from already connected device to be able to display it.

**Comment by devyte** [comment]
@beicnet the encryptionType() method is available in latest git. It is meant to be used over the results of a wifi scan, and takes an index as an argument.
Look at ESP8266WiFi/WiFiScan example, and [docs](http://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/scan-class.html?highlight=scan#encryptiontype).
I don't think there is a way to get the encryption type directly for the AP to which the ESP's STA is connected. I could be wrong, but this is not the right place to dicuss these things. If you need further info, please refer to a discussion forum.
Closing due to usage error and documented feature.
