### ISSUE TITLE
If POST JSON.stringify($('form').serialize()) the first value is omitted. 

### ISSUE THREAD

**Issue by nardev** [esp8266/Arduino#3525]
Maybe it's unusual to submit for in that way, but just to report  that if you  use AJAX and submit form in one value as stringify and serialized value in it, the first value will be omitted..

For example if you put:

```
...
data: JSON.stringify($('form#mqtt').serialize()),
...
```
of Ajax code with POST

Than on device if you print:
```
  Serial.println(server->arg("hostname"));
  Serial.println(server->arg("port"));
  Serial.println(server->arg("username"));
  Serial.println(server->arg("password"));
```
The hostname will be omitted.. or any other first value... probably because there is no &sign, which i assume is used as delimiter or  so...

**Comment by NdK73** [comment]
Maybe my understanding on what you're doing is is wrong (if so, please post some more details), but shouldn't you JSON-decode server->arg("data") ?

**Comment by nardev** [comment]
Actually, this is jquery js thing.. yes server gets data ok but doesn't recognize the first one.. anyway... just notice..

**Comment by devyte** [comment]
I don't understand the issue. Please put a minimal sketch that shows what you are trying to do.
As far as I know, the ESP8266Webserver does not decode json. It received the json data as a string, and puts it in arg "plain", so you would get it on the server side like this:
DynamicJsonBuffer buffer;
JsonObject & json = buffer.parseObject(server.arg("plain"));

In addition, the ESP8266Webserver can't handle simultanous requests. In other words, if it is handling e.g.: a POST, and a GET comes in, it may not behave correctly. I was using it exclusively until recently, but I was forced to switch to the AsyncWebserver, because modern browsers are incapable of serializing HTTP requests.

**Comment by nardev** [comment]
It's ok, you can delete this thread...

**Comment by vicnevicne** [comment]
We don't "delete this thread". Instead, could you please "close the issue" on the GitHub page ?
