### ISSUE TITLE
Missing nodemcu board after switching from Board Manager Version to Git Version in mac

### ISSUE THREAD

**Issue by Bimblis** [esp8266/Arduino#3566]
I've been using Board Manager version 2.3, and I can revert to it in any moment. But after following the readme steps to prepare the Git version, the esp8266 boards dont appear.

![screen shot 2017-09-03 at 04 07 57](https://user-images.githubusercontent.com/3843523/30000018-8fc9fed0-905d-11e7-86b7-5e55e5a8e46c.png)

![screen shot 2017-09-03 at 03 54 22](https://user-images.githubusercontent.com/3843523/30000017-894d8554-905d-11e7-9c63-1b8d5b6770de.png)

I have emptied the "additional board manager url" and deleted the 2.3 version from packages folder. Am I missing something?

**Comment by igrr** [comment]
Installation instructions do not make this clear, but you need to clone the git repository into either

- hardware/esp8266com/esp8266 directory in Arduino IDE (so the full path is Arduino.app/Contents/Java/hardware/esp8266com/esp8266),
- or into your sketchbook (by default, $HOME/Documents/Arduino, so the full path is $HOME/Documents/Arduino/hardware/esp8266com/esp8266)

Cloning into ~/Library/Arduino15/packages, as you did, will not work because Arduino IDE happens to use slightly different path rules for cores installed into the IDE/sketchbook and the ones installed into the downloaded packages directory.

**Comment by YUVARAJ1186** [comment]
igrr            IAM FACING PROBLEM WHAT U TOLD IN COMMENTS PLS EXPLAIN IT BRIEFLY BY STEP BY STEP IAM WAITING FOR U R REPLY

**Comment by kishan2006** [comment]
arduino 1.8.1 in board manager not desply esp 8266. so u tell me what i do ?
