### ISSUE TITLE
problem in uploading the sketch:

### ISSUE THREAD

**Issue by santhosh2409** [esp8266/Arduino#3645]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description

### Settings in IDE

Module:  			?Nodemcu 1.0(esp-12E module)?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

exec: "C:\\Users\\manikandan\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++": file does not exist
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

messages here

```while i try to upload the sketch of nodemcu esp8266 the arduino always shows that file doesn't exist...

may i know what was the problem.???

**Comment by devyte** [comment]
@santhosh2409 No Basic info, no IDE settings, no description. You pretty much ignored the issue template.
I am not aware of installation issues at the moment, I just tested installing. Most likely you have an installation problem. I suggest uninstalling and deleting whatever is left, and reinstalling from scratch following the installation instructions precisely.
If you need further assistance, please refer to esp8266.com or stackoverlow to figure out what you are doing wrong.
Closing due to lack of info and likely user error.
