### ISSUE TITLE
ESP8266WebServer not working when an IP address is specified

### ISSUE THREAD

**Issue by cg101** [esp8266/Arduino#3665]
I am trying to create a mesh network using ESP devices. So, all the ESPs in the network need to be in AP+STA mode.  After experimenting for some time, I have found out that a child ESP on the network cannot communicate with it's parent ESP using 192.168.4.1, because the child is in AP+STA mode and 192.168.4.1 refers to the child itself and not its access point.  So, as a workaround, I wanted to give the parent ESP a different IP address to listen on. But, It is not working for some reason.

Here's a simplified version of  my code for the parent ESP:

```
#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>
ESP8266WebServer server;
void setup() {
    Serial.begin(9600);
    WiFi.mode(WIFI_AP);
    WiFi.softAP("ssid", "password");
    WiFi.begin();
    IPAddress ip = (192,168,5,1);
    server = ESP8266WebServer(ip,80);
    server.on("/",hello);
    server.begin();
}    
void hello(){
  server.send(200,"text/plain","Hello");  
}
void loop() {
    server.handleClient();
}

```
I tried testing using my laptop before trying out with another ESP. But when I tried http://192.168.5.1 in the browser, I got no response. 

When I changed
`server = ESP8266WebServer(ip,80);`
to 
`server = ESP8266WebServer(80);`
I was able to get the expected result using http://192.168.4.1
But, I need the web server to listen on a different IP address. How can I do that?

**Comment by devyte** [comment]
@cg101 about your webserver, you probably have some usage error, because I can access it from both AP and STA interfaces.
I declare it like so:
ESP8266WebServer server(80);
then just add the .on() method calls in setup.

I think you have an issue with configuring the Wifi AP and STA network interfaces (IP address, gateway, mask, DHCP, etc). Please review the examples provided.

Also, if you really want a mesh, you should look at the NAPT gist by NeoCat, or at the esp-wifi-repeater project, or at the Espressif mesh api.

Closing, as there is no current issue.
