### ISSUE TITLE
system_deep_sleep() bad accuracy

### ISSUE THREAD

**Issue by Niesma** [esp8266/Arduino#3681]
Hello to the community, I am trying to improve the accuracy of the system deep sleep function. The problem that the esp8266 wakes up prematurely.
Could someone explain to me how this function works internally and the registers that it uses?
Thanks.

**Comment by devyte** [comment]
@Niesma no sketch, no basic info, no IDE settings. You pretty much ignored the entire issue template.
Try PR #3215 , there are comments relevant to deep sleep there.
If you need further assistance with usage, please discuss at a community forum. If you have a concrete example of code that should be supported, and doesn't behave as expected, please open a new issue, and provide a MCVE as well as the details requested in the issue template.
Closing due to lack of info, see #3655 .
