### ISSUE TITLE
Offline board definition for ESP8266

### ISSUE THREAD

**Issue by salmanfarisvp** [esp8266/Arduino#3695]
how can i install  the esp8266 board definition in arduino , it's most time consuming when i test/run esp in a new machine .

**Comment by devyte** [comment]
@salmanfarisvp installing in Arduino is documented, see readthedocs. If you want to install offline, most likely you just need to copy the relevant directories and restart the IDE (that's pretty much how installing the git version works).
Please request assistance at a community forum, this is an issue tracker.
Closing due to off-topic, see #3655 .
