### ISSUE TITLE
Arduino/libraries/ESP8266WiFi/examples/WiFiWebServer/WiFiWebServer.ino

### ISSUE THREAD

**Issue by electrocoder** [esp8266/Arduino#3906]
The example works in reverse.
Arduino/libraries/ESP8266WiFi/examples/WiFiWebServer/WiFiWebServer.ino

This is how the code works.

  // Match the request
  int val;
  if (req.indexOf("/gpio/0") != -1)
    val = 1;
  else if (req.indexOf("/gpio/1") != -1)
    val = 0;
  else {
    Serial.println("invalid request");
    client.stop();
    return;
  }

...

  s += (val)?"low":"high";

**Comment by devyte** [comment]
@electrocoder if you are using an ESP12, the built-in LED on GPIO2 is connected with inverted logic, i.e.: lights up when output is LOW. In this case, the current behavior of the example is expected, as it connects the specified GPIO value straight through.
Your code does a double inversion, which means that you expect the LED to light up with value "1" or HIGH. That is ok if it is your need, and it is more intuitive, but it is not how the hardware behaves, and it is not the purpose of the example.
Closing as expected behavior.
