### ISSUE TITLE
Client.available() reports false

### ISSUE THREAD

**Issue by akhil393** [esp8266/Arduino#4108]
#### Hardware
Hardware:			ESP-12E
Core Version:      	2.1.0

### Description

Client.available reports 0 , while there is data available to read. 

### Settings in IDE

Module:  			Generic ESP8266 Module?
Flash Size: 		4MB/1MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	40Mhz
Upload Using:		OTA / SERIAL
Reset Method:		ck / nodemcu

`client.print(String("POST ") + "/update HTTP/1.1\r\n" +
               "Host: " + host + "\r\n" +
               "X-THINGSPEAKAPIKEY: " + writeAPIKey + "\r\n"+
               "Content-Type: application/x-www-form-urlencoded\r\n"+
               "Content-Length: "+String(body.length())+"\r\n\r\n"+
                String(body)+"\r\n\r\n");`

`Serial.println(client.available());` 

The above command returns zero

but I run below command I get data 

`String line;
 line = client.readStringUntil('\r');
       Serial.println(line);`

**Comment by devyte** [comment]
@akhil393 this is expected. The method names say what they do. 
Available() tells you whether data has arrived or not. If there is latency between packets, available() will return false, even if there data on the way that hasn't been received yet.
ReadStringUntil() keeps trying to read data until the specified char is seen. If no data has arrived, it will read it into the buffer. If not, it will wait until data arrives, or a timeout expires.
Closing due to no issue.
