### ISSUE TITLE
Problem with Radiohead si446X

### ISSUE THREAD

**Issue by wizz777** [esp8266/Arduino#4390]
### Description

ets Jan  8 2013,rst cause:4, boot mode:(3,4)

wdt reset
load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v4ceabea9

### Settings in IDE

VID: 10C4
PID: EA60

### Sketch

```cpp

#include <Arduino.h>

#include <SPI.h>
#include <RH_RF24.h>

// Singleton instance of the radio driver
RH_RF24 rf24;

void setup() 
{
  Serial.begin(9600);
  if (!rf24.init())
    Serial.println("init failed");

}


void loop()
{
  Serial.println("Sending to rf24_server");
  // Send a message to rf24_server
  uint8_t data[] = "Hello World!";
  rf24.send(data, sizeof(data));

  rf24.waitPacketSent();
  // Now wait for a reply
  uint8_t buf[RH_RF24_MAX_MESSAGE_LEN];
  uint8_t len = sizeof(buf);

  if (rf24.waitAvailableTimeout(500))
  {
    // Should be a reply message for us now
    if (rf24.recv(buf, &len))
    {
      Serial.print("got reply: ");
      Serial.println((char*)buf);
    }
    else
    {
      Serial.println("recv failed");
    }
  }
  else
  {
    Serial.println("No reply, is rf24_server running?");
  }
  delay(400);
}

### Debug Messages

ets Jan  8 2013,rst cause:4, boot mode:(3,4)

wdt reset
load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v4ceabea9

**Comment by devyte** [comment]
@wizz777 The RF24 is a 3rd party lib, why are you reporting the issue in this repo?
Assuming you are using [this lib](https://github.com/PaulStoffregen/RadioHead) , I don't see why you would assume that it should work out of the box with the ESP. There is no specific statement about ESP support, and at a glance I don't see anything that is ESP-specific in the lib source code. Paul's lib's are aimed at the Teensy, so the timing requirements are completely different.
To be specific, your crash shows a triggered WDT, and I don't see a single yield/delay in Paul's lib, so it's very likely that an execution path through the lib api is taking way too long for the ESP.
Closing due to unsupported 3rd party lib.
