### ISSUE TITLE
Its reboots continuously

### ISSUE THREAD

**Issue by gioreva** [esp8266/Arduino#4758]
- Hardware:			ESP-07S
- Development Env:		Arduino IDE
- Operating System:		Windows 10

### Settings in IDE
- Module:  			Generic ESP8266 Module
- Flash Mode:			qio
- Flash Size: 		        4MB/1MB
- lwip Variant:                   v2 Lower Memory
- Reset Method:		ck
- Flash Frequency:	        40Mhz
- CPU Frequency:		80Mhz / 160MHz
- Upload Using:		SERIAL]
- Upload Speed:                115200

### Problem Description

I read ADC every 3 mS
WiFi Client
I use SPI
Few writing on serial.
Timer on interrupt.

If I remove ADC readings, stops the defect.
If I remove SPI, stops the defect.
If I remove WiFi, stops the defect.

### Sketch

Code:   (I apologize if it's complete, but whatever I remove it stop making the flaw)
https://pastebin.com/9yK2W1aU

### Debug Messages

Dump:  (I'm sorry, I can not install the STACK DUMP)
https://pastebin.com/cNwnUb4G

**Comment by devyte** [comment]
@gioreva the request is for an MCVE sketch. The referenced sketch is huge, with several dependencies on 3rd party libs. It is nowhere near minimal. 
In addition, sketches or logs should be included in the issue report, and not put on an external resource such as pastebin, because if it is removed in the future, it won't be accessible anymore when looking at this issue.
Finally, this is not a "my project doesn't work, please fix it" support forum. This is an issue tracker, meant for tracking issues in the core.
You need to minimize your code by removing different elements one by one, until you identify which one is causing the crash. If you don't know how to do that, get help at a community forum.
Off the top of my head, your use of HW timer0 jumps out at me. You probably don't need the hw timer for what you want, and even if you do need a hw timer, you might want to double check your implementation.
Closing.
