### ISSUE TITLE
cli() in tone/waveform, needed?

### ISSUE THREAD

**Issue by cranphin** [esp8266/Arduino#4830]
Hi!

I found a cli() (disable interrupts right?) call here:
https://github.com/esp8266/Arduino/blob/91bb97ddb30082f629b3ff2c8fc992c20fbad822/cores/esp8266/core_esp8266_waveform.c#L214

Is that needed at all? Why is it there? :)
It seems the only use in that source file, nowhere to re-enable interrupts, isn't that a problem?

Mostly trying to understand the code here, hope it's ok to have an issue for that :)

Thanks!

**Comment by devyte** [comment]
The issue template has been completely ignored. However, given that the referenced code is brand new, and that the description looks valid to me, I'm keeping this open.
@earlephilhower is that cli() call left over, or is there a matching sei() call missing?

**Comment by cranphin** [comment]
Oh, you never see the template if you create an issue by clicking a line of code in the repository, sorry :)

**Comment by earlephilhower** [comment]
Good eyes, @cranphin .  It was leftover, or so I thought.

I re-read the code again this morning and I see that while I *thought* I had guaranteed safe waveform start/stop without disabling IRQs, there is a 2-4 instruction window where nextTimeHighCycles could be trashed by the IRQ if it's called and updates the state for this waveform (due to the bitfield packing used to save memory).

I'll throw in a patch with proper IRQ disable/enable around the startWaveform region of danger late this week or early next.
