### ISSUE TITLE
board manaer showing error in downloading the board.

### ISSUE THREAD

**Issue by rohitmrig** [esp8266/Arduino#4950]
board manager is showing error in downloading the esp8266 board. I have been trying sine yesterday but the problem still persists. please help!?

**Comment by Pablo2048** [comment]
Nobody here can help You because of:
1. You have ignored issue template - your problem has probably nothing to do with the core so it has to be asked in forum (link was given in issue template which you have been completely ignored).
2. You given zero informations about any error messages given by program You use, so here is nothing what can be analysed.
