### ISSUE TITLE
ESP8266 light-sleep : how to get it

### ISSUE THREAD

**Issue by shw19791031** [esp8266/Arduino#5079]
## Environment

esp8266ex (ESP-12S)

## Application

- Waiting for incoming MQTT packet to boot the master device, use battery.
- So deep-sleep is useless, I have to use light-sleep keeping MQTT connection.

## Problem Description
- forced light sleep: ok!, 0.7~0.8mA current, but WIFI have to be disconnected. It is worse than deep-sleep.
- automatic light sleep: never success!, because I cannot manually halt (control) the CPU while DTIM period.

### Dear Espressif!

Please help me!

**Comment by devyte** [comment]
This repo doesn't belong to Espressif. Also, when you opened the issue, you were presented with a template with instructions, which you have completely ignored.
Off the top of my head, it sounds like what you're looking for is modem sleep.
Please refer to a community forum like esp8266.com for further assistance from peers. See issue POLICY doc for further details.
Closing.

**Comment by s0170071** [comment]
@devyte : right you are ! But unfortuately this issue is now one of the top ranking search results if you google for "esp8266 light sleep". For the benefit of simplicity I suggest to put some links here. 
And - to be honest - the sleep modes is one of the most obscure features of the ESP and there is not even an example sketch.

**Comment by devyte** [comment]
PRs with examples and doc updates are welcome!

**Comment by shw19791031** [comment]
Hi, [rtos issue 290](https://github.com/espressif/ESP8266_RTOS_SDK/issues/290#issuecomment-416787056), has discussed this problem completely, please refer it, thank you.

**Comment by s0170071** [comment]
> Hi, [rtos issue 290](https://github.com/espressif/ESP8266_RTOS_SDK/issues/290#issuecomment-416787056), has discussed this problem completely, please refer it, thank you.

@shw19791031 your link refers to the RTOS, this is an NonOS / Arduino issue.

Sleep still has some serious issues. Sometimes it sleeps and doesn't wake up, sometimes throws an exception, sometimes it just does not work at all. 
There is also a persistent aspect to it. Some SDK calls survive a reset+re-program so that the same code behaves differently on another device with a different past.

**Comment by drmpf** [comment]
Another approach is to use a nA timer and a fet to turn the ESP8266 on periodically.
