### ISSUE TITLE
HTTPClient::getString() returns stack-allocated object?

### ISSUE THREAD

**Issue by dalbert2** [esp8266/Arduino#5099]
### Basic Infos

- [X ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [X] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:			[ESP-12F]
- Core Version:			[2.4.2]
- Development Env:		[Platformio]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module (esp12e)]
- Flash Mode:			[qio]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[160MHz]
- Upload Using:		[SERIAL]
- Upload Speed:   [921600] (serial upload only)

### Problem Description

I have been struggling with an intermittent lockup (watchdog does not trip) when calling HTTPClient::GET() followed by HTTPClient::getString().  It appears to be timing dependent and seems to happen when the GET takes some time due to the server being busy.

While looking at this, I noticed that in ESP8266HTTPClient.cpp, the getString method appears to a return a stack-allocated object (which will go out of scope and be deleted when getString returns).  My C++ is rather rusty (mostly C and Java these days); but is this a mistake?:
```cpp
/**
 * return all payload as String (may need lot of ram or trigger out of memory!)
 * @return String
 */
String HTTPClient::getString(void)
{
    StreamString sstring;

    if(_size) {
        // try to reserve needed memmory
        if(!sstring.reserve((_size + 1))) {
            DEBUG_HTTPCLIENT("[HTTP-Client][getString] not enough memory to reserve a string! need: %d\n", (_size + 1));
            return "";
        }
    }

    writeToStream(&sstring);
    return sstring;
}
```

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

Sorry, I don't have  a short sketch to illustrate the problem, it is hard to reproduce reliably, but the problem snippet is here:
```cpp
	// Build URL of firmware version file on server
	snprintf(url, sizeof(url), "%s/%02X%02X.version", fwBaseURL, hw_type, hw_version);
	// Fetch firmware version file from server
	if (httpClient.begin(url)) {		
		httpClient.setTimeout(2500); //2.5s timeout
		int httpResult = httpClient.GET();
		if (httpResult == HTTP_CODE_OK) { // found
			// server version encoded as 0xTTMMmmpp (TT=hw type, Major.minor.patch)
			String serverFwVerStr = httpClient.getString(); 
			serverFwVer = strtoul(serverFwVerStr.c_str(), 0, 16); // hex_str->int
```
### Debug Messages

```
No useful debug output captured, but I have DEBUG_ESP_HTTP_CLIENT enabled now and will post the debug output next time I reproduce the problem.

```

**Comment by devyte** [comment]
The object is returned by value, which means that it is copied back. I think you're thinking of returning a pointer to a local variable.
A simple test you can do is to call this function and save the returned String to a local, then call some other function that uses stack right after (e.g.: write your own that has an array with specific numbers on the stack), then right after that check the saved String.  If it's corrupted, then there is a problem with something in String. If not, which is what I expect, then your issue is elsewhere.
Without an MCVE it's hard to help, I suggest spending effort on reducing your code to something that reproduces the issue, even if the issue only happens sometimes. Also, the MCVE sketch doesn't have to make sense, it just has to build and be able to reproduce the problem.
Closing in the meantime.
