### ISSUE TITLE
Changing Serial speed on the fly

### ISSUE THREAD

**Issue by josemariaaraujo** [esp8266/Arduino#5124]
I have an application where I change the serial port baudrate on the fly, after some negotiation (communicating with a power meter using IEC62056 optical interface).

My code works fine in 2.4.1, but if I try to update to 2.4.2 it stops working. I can communicate fine at the initial speed of 300bps, but after a speed change to 9600bps I don't get the data any more (no TX is done at the new speed).

I've tried to take a look at HardwareSerial.cpp and uart.c, noticing that there were some changes between versions, but I'm way out of my league in there.

For now I've gone back to 2.4.1, but would like to keep up with the latest versions.

My code is a bit messy (I'm in the process of refactoring it) and too big to share, but  I think I can come up with a simpler example code if needed when I get some free time.

**Comment by devyte** [comment]
@josemariaaraujo HardwareSerial and uart had serious issues in 2.4.1, hence the changes since then. The new implementation has been stress-tested and bandwidth-tested at high speed, there is even a device test for it. Although it's still possible for an issue to be present, I think it is unlikely at this time.
My suspicion is that your code was somehow relying on one of the bugs, e.g. timing.
Be aware that there is an autobaud detect feature available on the esp, I.e. the esp can figure out the baud after receiving a few bytes. This was added to the core recently, and tested successfully. I don't know if it helps you, but I thought I'd mention it.
Because of the current high level of trust in the hw serial, because there is no mcve that shows a core issue, because your issue depends on external hardware not available to developers here, and because you ignored the issue template, I'm closing this.
When you get free time, if you can make an mcve that shows the issue, that doesn't depend on specialized hw, feel free to open a new issue and fill out the required info.

**Comment by josemariaaraujo** [comment]
Tried to reproduce without success. 
Had another look at my code and the protocol with your comment about timing bugs in mind, and found that I wasn't respecting a minimum guard time between messages. The previous version was slower so I never noticed it.
Good call and thank you for your precious time in assisting me with my problem (which was totally my fault!). Keep up the good work!
