### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by REHolt** [esp8266/Arduino#5284]
### Problem Description

I just got a new computer and have been setting up Arduino software to develop a new Sketch on my ESP8266 hardware. I want to include OTA functionality and was wondering if Arduino IDE ESP8266 OTA now supports Python 3.7.1? Most of the (OLD) documentation still says install Python 2.7 because version 3.5 is not supported; however I saw a couple of posts saying it worked fine. I was hoping to get verification prior to installing.

Robert

**Comment by devyte** [comment]
Support for Python 3 should be considered experimental. It has been fixed and broken several times over. I have no idea what the current state is, because I dont use Python 3.
My suggestion: try and check if it works. If it does, awesome! Please add a comment with that. If it doesn't, open an issue with the details, investigate and find a fix, and then open a PR with it.
Closing due to not an issue.
