### ISSUE TITLE
Feature request: limit WiFiServer backlog size

### ISSUE THREAD

**Issue by douniwan5788** [esp8266/Arduino#5380]
Please limit the _unclaimed chain as listen backlog (http://man7.org/linux/man-pages/man2/listen.2.html)

https://github.com/esp8266/Arduino/blob/cd05bae0e8b69eea94adbf153eca4e7c9b96a901/libraries/ESP8266WiFi/src/WiFiServer.cpp#L164-L171

**Comment by d-a-v** [comment]
This is a _very_ fair request, to prevent DoS and memory filling.
We could use lwIP's  `tcp_listen_with_backlog` (instead of `tcp_listen`), but it does the same job as the `_unclaimed` list already implemented by brilliant core developpers. In both case we must limit that number.

What are the issues you are facing ?
What would be a fair amount of maximum backlogged connections with your use case ?
I think a maximum number between 4 and 8 should be sufficient for the general case.
If there are more incoming clients, their tcp stack will have to wait for ESP to effectively accept/honor the previous ones or they will timeout without filling our memory.

Would you make a PR for that ?

I don't think this has any relation with #928, why do you think so ?

**Comment by douniwan5788** [comment]
> This is a _very_ fair request, to prevent DoS and memory filling.
> We could use lwIP's `tcp_listen_with_backlog` (instead of `tcp_listen`), but it does the same job as the `_unclaimed` list already implemented by brilliant core developpers. In both case we must limit that number.
> 
> What are the issues you are facing ?
> What would be a fair amount of maximum backlogged connections with your use case ?
> I think a maximum number between 4 and 8 should be sufficient for the general case.
> If there are more incoming clients, their tcp stack will have to wait for ESP to effectively accept/honor the previous ones or they will timeout without filling our memory.
> 
> Would you make a PR for that ?
> 
> I don't think this has any relation with #928, why do you think so ?

Sorry, it has nothing to do with #928, should I delete it? I just encounter with Links2004's post while googling this backlog problem

I am not familiar with Arduino, but if I have free time, I will make a PR.

My issue is https://github.com/arendst/Sonoff-Tasmota/issues/4460

**Comment by d-a-v** [comment]
> Sorry, it has nothing to do with #928, should I delete it?

No worry, I was just asking because you posted at the two places

> I am not familiar with Arduino, but if I have free time, I will make a PR.

This will be welcome !

**Comment by d-a-v** [comment]
Tasmota is currently releasing updates only using arduino core-2.3.0 (IMHO, until core-2.5.0 is out and has its chances).
#928 issue no longer happens with core-2.4.0 and later when lwIP-v2 is enabled, but the issue you are reporting here is still valid with any version of lwIP.

**Comment by devyte** [comment]
Pushing back.
