### ISSUE TITLE
ets Jan 8 2013,rst cause:4, boot mode:(1,0) wdt reset

### ISSUE THREAD

**Issue by frustrat01** [esp8266/Arduino#5452]
Having an issue with the ESP8266-01 by uploading the sensor data to the localhost.
The below shows the issues when I open the Serial Monitor in the Arduino

` ets Jan  8 2013,rst cause:4, boot mode:(1,0)

wdt reset
`
By the way, I have tried using the WiFiClient example to upload the dummy data to the localhost and it works. But it cannot work with uploading the sensor to the localhost. 
Anyone has the solution please help me to get rid of this issue ASAP

**Comment by frustrat01** [comment]
[ESP8266_upload.txt](https://github.com/esp8266/Arduino/files/2659929/ESP8266_upload.txt)
fgfsdg

**Comment by mateusz-szafraniec** [comment]
You completely ignored the issue template. Not a word about hardware, or version of library, sensors etc.

**Comment by devyte** [comment]
Previous comment is correct. Also, no explanation of what localhost is, is what uploading sensor data means, etc.
Closing due to lack of info.
I suggest seeking help at a community forum like esp8266.com or stackoverflow. This is an issue tracker, meant for tracking issues in the core hosted in this repo, and not for providing general help.
