### ISSUE TITLE
TLS error and I cannot receive any debug on my serial

### ISSUE THREAD

**Issue by shahabmusic** [esp8266/Arduino#5719]
I have nodemcu. My secure MQTT connection using pubsubclient returns rc=-2 which I believe is a network error. In mosquitto's log also shows "new connection" and then "client disconnected socket error".
So I am trying to debug and see whats happening during handshake. However I cannot activate debugging for some unknown reasons. 
I enabled debugging via the arduino ide menu and selected "SSL+TLS_MEM+HTTP CLIENT+HTTP SERVER" and selected serial as output.
I can see my comments and my own debug comments print out in serial window but nothing from arduino debugging tool get printed in serial window. Please help. I have stuck here with TLS and rc=-2 issue for 3 weeks now.

**Comment by devyte** [comment]
@shahabmusic when you opened this issue you were presented with an issue template, which has specific instructions and requests specific information. You have ignored it, and the information you provided is not enough to even begin a discussion.
In addition, this is an issue tracker, meant for tracking issues found in the core hosted in this repo, and not meant for general support. Your issue is related to a 3rd party lib, and doesn't hint at an issue with the core.

I suggest seeking help at a community forum like esp8266.com or stackoverflow.

Closing.
