### ISSUE TITLE
feedback form issues https://github.com/esp8266/Arduino/issues/5872#issue-420296439

### ISSUE THREAD

**Issue by kaihangchen** [esp8266/Arduino#5884]
I tried to change the hardware, but found a new problem, there is always a node can not find the mesh AP, for example, The first and second can occasionally communicate but the third will not find the meshAP。
Can you tell me your IDE settings? 
thank you very much.

**Comment by aerlon** [comment]
### Settings in IDE

- Module:  			NodeMCU 1.0
- Flash Mode:			dio
- Flash Size: 		4MB
- lwip Variant:   v2 Lower Memory
- Reset Method:		nodemcu
- Flash Frequency:	40Mhz
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:   115200

The way the mesh library works at the moment is that one node usually becomes the AP and the other nodes connect to it. So it is completely normal that the node with the lowest nodeID cannot find any AP to connect to (you can change this behaviour by modifying the `networkFilter` method). For me it looks like this:

![HelloMesh demo AP](https://user-images.githubusercontent.com/39123666/54473808-19efc800-47dd-11e9-9c9b-18eabb60a8bf.png)

Was that the issue you were having? Otherwise perhaps it is related to [this](https://github.com/esp8266/Arduino/issues/5032).

**Comment by earlephilhower** [comment]
This bug doesn't have a MCVE or even a clear description of the problem.  The author didn't respond at all to @aerlon , either.  Closing.  If there is a real issue please follow the form and give a meaningful bug title so we can understand the issue.
