### ISSUE TITLE
Error installing esptool

### ISSUE THREAD

**Issue by hrshovon** [esp8266/Arduino#613]
esptool download error.
![selection_002](https://cloud.githubusercontent.com/assets/6175616/8889118/a6499104-32ed-11e5-936b-a5740f8af99c.png)

**Comment by tytower** [comment]
Yes I confirm this seems to be a bug and a few others have it too . reportedly only on Linux 32 bit

**Comment by tytower** [comment]
There is no /releases/  directory

**Comment by igrr** [comment]
Whoops. We really don't have a linux-32 build of esptool for this version. Sorry guys.
@hrshovon since you are running linux 32bit, could you please help everyone by building esptool and providing an archive?
```bash
git clone https://github.com/igrr/esptool-ck.git
cd esptool-ck
git checkout 0.4.5
make dist
```
This will create a tar.gz archive which you can upload somewhere, and i'll make it available for download.
Thanks.

**Comment by hrshovon** [comment]
Done,hope it helps :)
https://www.dropbox.com/s/hirp6j1udt5g0c5/esptool-0.4.5-linux32.tar.gz?dl=0

**Comment by igrr** [comment]
Thanks!
I have pushed new staging package, version number is 1.6.5-988-gfd1d9da.
http://arduino.esp8266.com/staging/package_esp8266com_index.json
Please give it a go.

**Comment by FredAnoniem** [comment]
Thanks guys! It works on my Linux 32.

**Comment by tytower** [comment]
me too Thanks
