### ISSUE TITLE
How to OTA Updation via HTTPS(ESP8266)?

### ISSUE THREAD

**Issue by wounder123** [esp8266/Arduino#6452]
In esp8266 ,how to update  the bin file in ESP8266 from a webserver using **HTTPS**?

i have tried ,but http update failure error come.

**Comment by miprochip** [comment]
https://esp8266-arduino-spanish.readthedocs.io/es/latest/ota_updates/readme.html

**Comment by wounder123** [comment]
It's http but i need HTTPS(domain name is started at https://)

**Comment by wounder123** [comment]
ARDUINO IDE return error:::::
no matching function for call to 'ESP8266HTTPUpdate::update(BearSSL::WiFiClientSecure&, const char [48])'
is it needed to update my core version ESP8266(it is now 2.4.2)?
any other field needed to include?

**Comment by Jeroen88** [comment]
This is not a help desk but an issue tracker!

You need [this](https://github.com/esp8266/Arduino/blob/e56aed65408fad7e5eebbbcf265f6f34c5bca70c/libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h#L98) function.

If you want to use a fingerprint, which I asume because you want to pass a const char[], you should pass it to client before you call update. You can see [here](https://github.com/esp8266/Arduino/blob/e56aed65408fad7e5eebbbcf265f6f34c5bca70c/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h#L81) that a fingerprint is a const uint8_8[20]
