### ISSUE TITLE
Generating large dynamic response -> ESP8266 WDT crash and memory corruption

### ISSUE THREAD

**Issue by slackwaree** [esp8266/Arduino#6648]
Hello,

Although there was a similar thread it did not provide definitive solution for my problem. 

I'm generating a table dynamically, the entries are drop down menu lists which are SET to a default value depending on the global variables.

The code might be a bit too long to post it here:
https://pastebin.com/YAnZ2MFw

Now just right off the bat there is already an issue even if I would just try to Serial.println the generated string and we not even talking about the webserver yet, 10 times in a row it kills the ESP8266. If I introduce a delay(500) between the serial prints then at least that works.

Let's move on the web part, as the commented out attempts show I tried pretty much everything, the behavior is that sometimes entry 1 and 2 gets printed, at next page reload nothing, so some serious memory corruption is going on..

What I tried:

1, First was the attempt to have a big response string  which contains the header of the HTML + 10x generated forms + footer then using a server.send to send that back to the client (would be too easy right?! yeah sure its not working)

2, After reading a bit that the device cannot throw this much data back I have tried with CONTENT_LENGTH_UNKNOWN and put in server.sendContent for the generator and send the footer of the html at the end with server.sendContent as well, doesn't work.

3, OK 3rd attempt I tried the 2nd version however first I run a generator loop just to calculate how long the generated content will be and add the 3 together (header+generated+footer), set the content length and then send the data back with server.sendContent doesn't work, device does not segfault but weird behavior again (eg for first time entry 1 and 2 displayed then that part is missing and the content length is keep changing which means there are some corruption with the string variables).

As I noticed with printing out the length of the string variables: one generated entry is about 2995 characters, I found someone saying that the device can send back like 3k so it's kinda border line.

I have found something about server.send_P but that is for files, I don't work with files.

So any simple answers how to fix my code?

Thanks!

**Comment by TD-er** [comment]
Without looking at your code, but just basing on the issue description.

Try not to generate long strings, but send them directly to the receiving end.
There is no need in having the entire page rendered in memory. So you may want to have a look at chunked transfer for the webserver part.
For sending to serial, try to monitor the amount of data still present in the buffers.
If those buffers are full, the baud rate simply cannot keep up with the pace in which you are sending data. The writes will then become blocking calls which may lead to other issues like WDT reboots, WiFi disconnects, filled buffers of unhandled network traffic etc.

If you're still trying to generate long strings, use the reserve function on that string object immediately after constructing it so you can prevent memory fragmentation due to many re-allocations by the String object.

Using chunked transfers do work and it also removes the need to compute the content length.
It does require you to send an empty reply as last content to let the client know the transfer has finished.

In my project I manage to generate web pages at lightning speed of which some pages are exceeding the total size of heap memory available.
