### ISSUE TITLE
Android mdns responsive in one example but not in other  

### ISSUE THREAD

**Issue by rajnish1959** [esp8266/Arduino#6669]
### Basic Infos

- [yes ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ yes] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [yes ] I have tested that the issue is present in current master branch (aka latest git).
- [yes ] I have searched the issue tracker for a similar issue.
- [ no] If there is a stack dump, I have decoded it.
- [yes ] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12|
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE|]
- Operating System:		[Android/Windows7]

### Settings in IDE

- Module:  			|Nodemcu|other]
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB}
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200|other] (serial upload only)

**Comment by devyte** [comment]
@rajnish1959 Your answer is in your question: it works in our example, but not in the code in the ttapa repo. Most likely there is something wrong in that code, so your question should be asked over there.
Please be aware that this is not a general support forum for requesting generic help. This is an issue tracker, meant for tracking issues in the core code. For general help regarding your code or 3rd party code that you use, please refer to a community forum like esp8266.com or stackoverflow, or ask the 3rd party code authors.
Closing due to not a core issue.
