### ISSUE TITLE
wemos D1 mini parallel output

### ISSUE THREAD

**Issue by alex1379** [esp8266/Arduino#6789]
I'm running 2 strips of ws2812 on Wemos D1 mini with FastLED library. Strip1 on D1 is 448 leds and strip2 on D2 172 leds. Also there's an IR receiver on D4. I'm getting occasional resets on the board. Wifi is not used.
I'm guessing it might be too many leds and too fast FPS. My question is does esp8266 support parallel output without any shift registers? If yes, on which pins?
Any feedback is really appreciated!

**Comment by devyte** [comment]
I think all of them except GPIO16. Beware the forbidden pins used for spi flash etc.
"Use the source, Luke!" => look at the implementation of digitalWrite().
Also, you ignored the issue template.
Also, this isn't the right place to ask general help questions. Please refer to a community forum like esp8266.com or stackoverflow for that.
Closing due to not compliant.
