### ISSUE TITLE
LittleFS installation question

### ISSUE THREAD

**Issue by yaroslav7522** [esp8266/Arduino#6939]
Hi. How can I install LittleFS correctly? After instalation I have an error about additional libraries are missing, for example "fatal error: flash_hal.h: No such file or directory"

**Comment by devyte** [comment]
@yaroslav7522 LittleFS isn't "installed", it is part of the core. That means that you install our core, and then you just use LittleFS like in the examples.
If you're having a compile error, then most likely you have an installation issue, because our core build is covered by CI to make sure building isn't broken. I suggest doing a clean install from scratch of both your IDE and our core, as per the instructions on readthedocs.
If you need further help, please ask at a community forum like esp8266.com or stackoverflow, because this is an issue tracker meant for tracking issues in the core, and not meant for general support questions.
Closing.
