### ISSUE TITLE
How to flash Bin file from Arduino to esp8266 in batches

### ISSUE THREAD

**Issue by droidbreaker** [esp8266/Arduino#7137]
Respected Sir,
                    I would like to flash same code for more than 200 ESP-8266 chips by using bin file from arduino IDE.
Here what i will use is Frog board: https://www.aliexpress.com/item/32827814637.html for easily flashing ESP8266, and programmer i will use is : https://www.espressif.com/sites/default/files/tools/flash_download_tools_v3.6.8.zip

But i dont know the configuration and how to start with i would like to flash multiple ESP chips simultaneously. But required configuration procedure that what to select and what not to. and how many files should i flash in single chip and what address should i start Bin file from: I think it will be 0x000000 at start. But rest i dont know which file to use in other addresses lines to upload arduino code bin file.
Kindly help with procedure. I will use minimum 4-5 frog board which will be connected via USB and will flash all at once in Multi mode.
So kindly share me procedure to flash my arduino code into ESP, because i have searched and i have not found any full proof solution to work it out.

**Comment by devyte** [comment]
The first flashing has to be over serial, I suggest an app that implements ota or web updates. After that you can update in batch remotely with scripts, either with espota.py or generic web posting. 
The issue template you saw when opening this clearly explains that this is not the right place to ask "how do I..." type questions. This is an issue tracker, meant for tracking issues in the core, and not meant for general support questions. For general support please refer to a community forum like esp8266.com or stackoverflow.
Closing due to not compliant.
