### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Picman1** [esp8266/Arduino#7151]
### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ X] I have tested that the issue is present in current master branch (aka latest git).
- [ X] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ X] I have filled out all fields below.

#### Platform

- Hardware:				[Wemos D1 R1]
- Core Version:			[2020/03/13]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Wemos D1 mini r1]
- Flash Mode:			[]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

Does not compile with settings above, reason:
exit status 1
'char g_szRecvBuff [7000]' previously declared here

-- In line 16

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

Stock standard

**Comment by devyte** [comment]
Building the core is covered by CI. If it doesn't build for you, the most likely reason is that you have an installation issue.
Building of 3rd party libraries is up to the library author. Whether it builds or not and whether building is covered by CI is up to him. 
Building your sketch is on you. If it doesn't build, you can request help at a community forum like esp8266.com or stackoverflow, but not here, because this is an issue tracker, meant for tracking issues in the core, and not for general support. 
Closing due to not compliant.
