### ISSUE TITLE
Is it possible to trigger a reboot into ROM bootloader from app code?

### ISSUE THREAD

**Issue by AlessandroAU** [esp8266/Arduino#7289]
Lets say I'm running some application code, is there any way I trigger a reset/reboot into its ROM bootloader entirely from code?

**Comment by devyte** [comment]
The question doesn't make any sense. My understanding is that the esp boots into rom, which then boots into flash at 0x0, i. e. eboot, which then boots your app at address 0x1000.
Not the right place to ask such questions, this is an issue tracker, not a general support forum. Our time here as maintainers/developers is meant for maintaining/developing, and not for help requests.
Closing due to not compliant.
