### ISSUE TITLE
Error: "class" has not been declared when including library (since 2.7.0)

### ISSUE THREAD

**Issue by wathui99** [esp8266/Arduino#7483]
Hello,
**Since version 2.7.0,** when I include this library: https://github.com/intrbiz/arduino-crypto
This error has occured: **"AES"("SHA256HMAC",...) was not declare in this scope**
How to solve it? thanks a lot!

**Comment by devyte** [comment]
The issue template was ignored, so no context.
Also, this is an issue tracker, meant for tracking issues in the core hosted in this repo. We don't maintain 3rd party libraries, nor do we offer general help.
Also, our latest release has an experimental Crypto wrapper implemented on the bearssl functions, see Ceypto.h. I suggest looking at that as a replacement. 
Closing due to not compliant.
