### ISSUE TITLE
Daylight saving time zone adjust

### ISSUE THREAD

**Issue by Delanjp949** [esp8266/Arduino#7783]
I'm in Adelaide Australia.  GMT +9:30 or GMT +10:30.  Setup as per intruction.  The clock at the moment is 1 hour fast.  Is there any way to adjust this.  Is there a Option available to add for this.

**Comment by d-a-v** [comment]
Check the [NTP-TZ-DST example](https://github.com/esp8266/Arduino/blob/f3521da173e7995f3d7e4a657fed5ab081de2ff6/libraries/esp8266/examples/NTP-TZ-DST/NTP-TZ-DST.ino#L42) available from the Arduino IDE (`Files>examples>esp8266>NTP-TZ-DST`).
Your timezone would be [`TZ_Australia_Adelaide`](https://github.com/esp8266/Arduino/blob/f3521da173e7995f3d7e4a657fed5ab081de2ff6/cores/esp8266/TZ.h#L319) (instead of `TZ_Europe_London` in the example).

**Comment by devyte** [comment]
Closing due to not compliant.
