### ISSUE TITLE
restore configuration after LowPowerDemo.ino on ESP8266

### ISSUE THREAD

**Issue by clotaireFrance** [esp8266/Arduino#7890]
Hello

I've tried "LowPowerDemo.ino" on a ESP8266

but now I want to change and test another project on my ESP

but It doesn't want to run as before?

How can I "reset" the configuration witch seems to have been modified by  "LowPowerDemo.ino"

Thank You

**Comment by Tech-TX** [comment]
The code doesn't change _anything_ in the configuration; in fact I went out of my way to insure that it doesn't write to Flash at any time.  The 'Light Sleep' tests may bugger the ets_timers, but the following Deep Sleep RESET or a power cycle will correct that.  Any configuration settings you change in the Tools menu are 'sticky', and will persist, but that's not the fault of the demo, that's you.

With **all** uploads, you need to erase "Only Sketch" in the **Tools: Erase Flash setting** _at a bare minimum_.  If you have issues, always try the "**Sketch + Wifi Settings**" or "**All Flash Contents**".  Neither of those should be needed unless there's something left over from your _OTHER_ experiments, as I don't write to Flash, only the RTC RAM.  A power cycle clears the RAM.

As a strong suggestion, do not EVER delete the Issue template.  You're likely to get this whole issue dismissed because you didn't follow simple directions.
