### ISSUE TITLE
ESP8266 crashes if "const String array[] PROGMEM" is present in code

### ISSUE THREAD

**Issue by enjoyneering** [esp8266/Arduino#8682]
### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [* ] I have searched the issue tracker for a similar issue.
- [* ] If there is a stack dump, I have decoded it.
- [* ] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12]
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[qio]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[80Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

ESP8266 crashes if "const String array[] PROGMEM" is present in code

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Arduino.h>

#define TEST_00 "test_0"
#define TEST_01 "test_1"
#define TEST_02 "test_2"

const String test[] PROGMEM =
{
  TEST_00,
  TEST_01,
  TEST_02
};

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}


```

### Debug Messages

```
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3424, room 16 
tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8 
tail 0
chksum 0x2b
csum 0x2b
v00040b60
~ld
```

**Comment by mcspr** [comment]
`PROGMEM` changes section of the object, and all its members. Since you have a const object with a constructor, at runtime it has to call `String::String()` which will try to write to *address pointing at flash region*, which does not work

This came up recently in `unordered_map` discussion; If you want something more complex than `const char[]`, you might want to look at something like `std::string_view` plus also make it `constexpr` instead of `const`. We still have the problem of 'binding' the char string itself to a flash memory section, so the general approach would be to have 'constexpr char[] PROGMEM` which is automatically converted in functions / classes / methods to `StringView` class. String literals (`const char* foo = "bar";`) are in RAM by default, and iirc we would have problems with SDK API if we change linker scripts to force them into flash and some more unexpected behaviour because of that (but, may be wrong about that part)

Some references
* https://github.com/esp8266/Arduino/issues/8575 (as to why you may not see crash dump at boot)
* https://github.com/fabianoriccardi/melody-player/commit/a0a9a7ad6613e1c02472603d987a4d24116f56be (example implementation)
* https://github.com/xoseperez/espurna/blob/35656314aa5f452a5b09fbb3acbe508fde9e280a/code/espurna/types.h#L77-L177 (another example)
* https://github.com/xoseperez/espurna/blob/35656314aa5f452a5b09fbb3acbe508fde9e280a/code/espurna/terminal.cpp#L356-L375 (which I think does specifically what you want; have some PROGMEM struct with strings and so something with it)
