### ISSUE TITLE
String: add debugging message in case of allocation failure

### ISSUE THREAD

**Issue by d-a-v** [esp8266/Arduino#8779]
[Following this comment](https://github.com/esp8266/Arduino/commit/04fe8e8b58707147b751cc45b8b97adb7bacace5#r94540003)

[Change would be there](https://github.com/esp8266/Arduino/blob/137d421fdd27fc612c8a63ec6dda02a14a28771f/cores/esp8266/WString.cpp#L250)

Cc: @MacDada

**Comment by MacDada** [comment]
Wow, I did not expect there would be a response o.O Thanks and good luck! <3

**Comment by MacDada** [comment]
> Change would be there

Out of curiosity: what kind of change do you have in mind?

1. From my perspective, the best option would be an exception.
* `+` Simple to detect problem, easy to handle "globally".
* `-` But there can not be any exceptions on Arduino :/
2. Second option is to make `replace` return `bool` to signal if it was successful.
* `+` Clear interface
* `-` Could be a little bit backwards incompatible (interface change), but since it returns `void` now, probably nobody really "checks" what it returns RN, so for the new code anybody can just start checking.
*  `-` Check and and handle each and every time it is used might be cumbersome
3. Another way is to add a third parameter to `replace`: a reference bool to check if succeeded
* `+` more BC than above
* `-` even more cumbersome than above (having to create a var in advance on usage)
4. Log info to serial
* `-` You have to be lucky to observe serial monitor and notice
* `+` But actually that's the first thing I do when there is a problem: log to serial everything I suspect might be connected to the issue -> so it would have helped me to spot the problem much faster
5. Any other ideas?

**Comment by d-a-v** [comment]
Yes, I think a message in debugging mode is the best we can do when exceptions are not enabled.
