### ISSUE TITLE
esp8266 eeprom read crash 

### ISSUE THREAD

**Issue by ADJ7WTB** [esp8266/Arduino#903]
Does any one know why exception 28 crash on esp8266. I write data to eeprom. But when I want to read it. The esp8266 crash. 
My code:
```c++
#include <EEPROM.h>

Struct mydata{
  char ssid;
  char pass;};

void setup(){ 
Serial.begin(9600);
EEPROM.begin(4096);
Readeeprom();
}
void Readeeprom (){
const char* said;
const char* pass;

mydata Varcustom;

EEPROM.get(0, Varcustom);
//Exception 28 error begin here
Serial.println(Varcustom.ssid);// does not show this print
}
```
Any help??

**Comment by ADJ7WTB** [comment]
My write to eeprom code look like this

My code:
#include <EEPROM.h>
Struct mydata{
char ssid;
char pass;
};

void setup(){ 
Serial.begin(9600);
EEPROM.begin(4096);
WriteEeprom();
}
void WriteEeprom (){
mydata Varcustom = {"ssid","password"};
EEPROM.put(0, Varcustom);
}

The short simple version

**Comment by igrr** [comment]
This code doesn't look like it should work.
If you need to save strings to EEPROM, take a look at this example: https://github.com/tzapu/WiFiManager/blob/master/WiFiManager.cpp#L164-L194

**Comment by ADJ7WTB** [comment]
Thanks for reply. 
According to arduino ide document it should work.
I tried converting string to char. Then write it to eeprom. Should work but it gives me the same error. Will look at that code anyways.

**Comment by igrr** [comment]
Your writing code is not well-formed because struct fields are `char`s, and you are initializing these fields with `const char*`. This is undefined behaviour in C++.

Reading code doesn't make sense (you are only reading a single character for `ssid` and single character for `pass` field), but it shouldn't crash. I modified your sample a bit (changed baud rate, changed `Struct` to `struct`, added a `Serial.println` to the end of setup function): https://gist.github.com/igrr/cfd5411dccb2c6764e41. It runs without issues on my side.

**Comment by ADJ7WTB** [comment]
Thanks for the help. Atleast it's not crashing.

**Comment by asetyde** [comment]
I think is not good idea , use "block function" for me is stable and best choice 

void eeprom_read_block(uint8_t * data, uint32_t address, size_t len) {
  int i;
  for (i = 0; i < len; i++) {
    data[i] = EEPROM.read(address + i);
  }
}

void eeprom_write_block(uint8_t * data, uint32_t address, size_t len) {
  int i;
  for (i = 0; i < len; i++) {
    EEPROM.write(address + i, data[i]);
  }
  EEPROM.commit();
}

**Comment by asetyde** [comment]
simple and full tested
